server:
  port: 80

spring:
  security:
    user:
      name: pgd
      password: 123456

  datasource:
    username: zjftest
    password: testdb!
    url: jdbc:mysql://192.168.0.202:3306/mydb?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useAffectedRows=true


  jpa:
    database: mysql
    database-platform: mysql
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
